networks:
  app:

services:

  app-docker:
    container_name: app-docker
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql_db
      - phpmyadmin
    networks:
      - app

  mysql_db:
    image: mysql:8.3
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - app
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app